#' This are preset arguments
#'
#' @name CoTiMAStanctArgs
#' @export CoTiMAStanctArgs
#'
CoTiMAStanctArgs<-list(test=TRUE,
                       scaleTI=TRUE, scaleMod=FALSE, scaleClus=FALSE,
                       scaleTD=FALSE, scaleLongData=FALSE, scaleTime=1/1,
                       scaleTimeAuto=NULL,
                       savesubjectmatrices=FALSE, verbose=1,
                       datalong=NA, ctstanmodel=NA, stanmodeltext = NA,
                       iter=1000, intoverstates=TRUE,
                       binomial=FALSE, fit=TRUE,
                       intoverpop="auto", stationary=FALSE,
                       plot=FALSE, derrind="all",
                       optimize=TRUE,
                       optimcontrol=list(init = "random",
                                         initsd = 0.01,
                                         #sampleinit = NA,
                                         #deoptim = FALSE,
                                         estonly = FALSE,
                                         tol = 1e-08,
                                         #decontrol = list(),
                                         stochastic = TRUE,
                                         priors = TRUE,
                                         carefulfit = TRUE,
                                         bootstrapUncertainty = FALSE,
                                         subsamplesize = 1,
                                         parsteps = c(),
                                         parstepsAutoModel = FALSE,
                                         groupFreeThreshold = 0.5,
                                         plot = FALSE,
                                         #hessianType = "numerical",
                                         #stochasticHessianSamples = 50,
                                         #stochasticHessianEpsilon = 1e-05,
                                         is = FALSE,
                                         #isloopsize = 1000,
<<<<<<< HEAD
                                         isitersize = 1000,
                                         isESS = 100,
=======
>>>>>>> e9c5ed7ddd285391c3a8f2b8cf608815afccd1ce
                                         finishsamples = 1000,
                                         tdf = 10,
                                         chancethreshold = 100,
                                         finishmultiply = 5,
                                         lproughnesstarget = 0.2,
                                         cores = 2,
                                         matsetup = NA,
                                         nsubsets = 100,
                                         stochasticTolAdjust = 1000),
                       verbose = 0,
                       nlcontrol=list(),
                       #nopriors=TRUE,
                       priors=FALSE,
                       chains=2,
                       resample=NULL,
                       cores=2,
                       warmup=500,
                       inits=NULL, forcerecompile=FALSE,
                       savesCompile=TRUE,
                       savescores=FALSE, gendata=FALSE,
                       control=list(adapt_delta = .8, adapt_window=2, max_treedepth=10, adapt_init_buffer=2, stepsize = .001),
                       vb=FALSE)
